### ISSUE TITLE
Error While Building on Docker

### ISSUE THREAD

**Issue by btphan95** [nikhilno1/healthy-or-not#2]
Hello,

While trying to build through Docker, I received the following error:

`Traceback (most recent call last):
  File "food-detector.py", line 42, in <module>
    data = ImageDataBunch.single_from_classes(path, classes, tfms=get_transforms(), size=224).normalize(imagenet_stats)
  File "/usr/local/lib/python3.6/site-packages/fastai/vision/data.py", line 166, in single_from_classes
    return sd.label_const(0, label_cls=CategoryList, classes=classes).transform(ds_tfms, **kwargs).databunch()
TypeError: transform() got multiple values for argument 'tfms'`

It seems a case of newer versions of libraries no longer working with this code. Could you please post a requirements.txt file with the library versions that work for you? Thanks.

**Comment by nikhilno1** [comment]
Can you change tfms to ds_tfms and try?

**Comment by btphan95** [comment]
That works! I made a pull request to fix the issue.
